### ISSUE TITLE
defbefore :parameters are not checked

### ISSUE THREAD

**Issue by piranha** [frankiesardo/pedestal-swagger#5]
Not sure how this can be done, but something like [load-pet-from-db](https://github.com/frankiesardo/pedestal-swagger/blob/master/sample/src/sample/service.clj#L85) is not going to have it's parameters validated, coerced and added to swagger documentation. I've defined something like this:

```
(swagger/defbefore load-thing-from-db
  {:parameters
   {:path {:id s/Int}}
   :responses {404 {:description "Thing is not found"}}}
  [{:keys [request] :as ctx}]
  (if-let [thing (db/get-thing
                   (-> request :path-params :id)
                   (-> request :user-id))]
    (assoc-in ctx [:request :thing] thing)
    (assoc (terminate ctx) :response {:status 404})))
```

And it breaks with an error: 

```
org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
```

That's because `(-> request :path-params :id)` returns a `String` rather than `Integer`.

**Comment by frankiesardo** [comment]
Mhmh, have you included the `coerce-params` interceptor at the top of your route paths? That should take care of it.

**Comment by piranha** [comment]
Well, I have it included, since it works when I specify this `:parameters {:path {:id s/Int}}` in a regular handler.

**Comment by frankiesardo** [comment]
The sample app ` load-pet-from-db` correctly coerces it to a `Long` and the documentation is inherited. Can you work from there and see if you're doing anything differently?

Once caveat is that the final endpoint must be a `swagger/..` interceptor. That was in order to make sure that non-swagger endpoint are not documented if the end user doesn't want to.

**Comment by piranha** [comment]
I found what was the problem! I had another interceptor (for checking authentication), which didn't define it's parameters properly, and that was interfering. It works now properly, thanks!
