### ISSUE TITLE
Schema-less objects cannot be defined inline

### ISSUE THREAD

**Issue by oliyh** [frankiesardo/pedestal-swagger#6]
```clojure
(s/defschema SomeObject
    {:foo s/String
     :bar {s/Keyword s/Any}})
```

The swagger json for this object is not produced correctly - the `:bar` key is omitted altogether but I expected it to produce a schema for a JSON object.

One dirty fix is to use
```clojure
(s/defschema SomeObject
    {:foo s/String
     :bar s/Any})
```
But this could be a boolean or a string as well as an object; a slightly better but more verbose way is the following:

```clojure
(s/defschema AnyObject
    {s/Keyword s/Any})

(s/defschema SomeObject
    {:foo s/String
     :bar AnyObject})
```

**Comment by ikitommi** [comment]
the root cause is in ring-swagger, which is dropping the `Anything` schemas as there was no such thing in swagger 1.2. As 2.0 spec supports `additionalProperties` in schema objects, I believe this could work. I'll write an issue to r-s about this.

**Comment by ikitommi** [comment]
grabbed and modified Juan Patten's codes in ring-swagger. If schema has a key `s/Keyword`, it's values is used as additionalProperties. Not 100% sure this is how it should work. Please give it a spin.

https://github.com/metosin/ring-swagger/blob/9b2f7169762577a0c43c13bb6075152167372915/test/ring/swagger/swagger2_test.clj#L245-L272

adding this dependency should work:

```clojure
[metosin/ring-swagger "0.19.6-SNAPSHOT"]
```

**Comment by oliyh** [comment]
Kiitos @ikitommi
