### ISSUE TITLE
Cannot reuse schemas within others - metadata is merged

### ISSUE THREAD

**Issue by oliyh** [frankiesardo/pedestal-swagger#7]
I have the following schemas used as body params for two methods on the same path

```clojure
(s/defschema UuidParam
    {:uuid s/Str})

(s/defschema Entry
    {:email s/Str})

(s/defschema Entries
    {:entries [(merge Entry
                              UuidParam)]})

(swagger/defhandler submit-entry
  {:summary "Submit an Entry"
   :parameters {:body Entry}
   :responses {201 {:schema UuidParam}}}
  [req]
  {:status 201 
   :body {:uuid "1234"}})

(swagger/defhandler list-entries
  {:summary "List all the entries!"
   :parameters {}
   :responses {200 {:schema Entries}}}
  [req]
  {:status 200 
   :body {:entries [{:uuid "1234"
                           :email "foo@bar.com"}]})

(s/with-fn-validation 
  (swagger/defroutes routes
    {:title "Entry System"}
    [[["/entries" {:post submit-entry
                       :get list-entries}]]]))
```

Expected behaviour is that the swagger schema for POST /entries is `{:email s/Str}` and the schema for GET /entries is `[{:email s/Str, :uuid s/Str}]` but what happens is that they both have the same schema of `[{:email s/Str, :uuid s/Str}]`. Initial investigation suggests the second schema definition of `Entries` retains the meta of the subschema `Entry`.

**Comment by ikitommi** [comment]
hi,

root-cause is that both `Entry` and inner-schema of `Entries` have same name (meta-data seems to be merged from right to left in Clojure). There is no way Ring-Swagger could know which of the two models to use. 

this should help:

```clojure
(s/defschema Entries
    {:entries [(s/schema-with-name (merge Entry UuidParam) "EntryAndUuidParam")]})
```

or just dissoc the name from the schema and let ring-swagger figure a good name for the inner anonymous schema (would be `EntriesEntries` btw ;)):

```clojure
(s/defschema Entries
    {:entries [(with-meta (merge Entry UuidParam) nil)]})
```

hope this helps.

**Comment by ikitommi** [comment]
... I'll add note to the[schema-tools](https://github.com/metosin/schema-tools), so that it's `merge` would also the schema-names. Would need to call by the client, but would be much cleaner:

```clojure
(require '[schema-tools.core :as st])
(s/defschema Entries
    {:entries [(st/merge Entry UuidParam)]}) ;; name would be ~"EntryAndUuidParam"
```

**Comment by ikitommi** [comment]
with `[metosin/schema-tools "0.4.0"]`:

```clojure
(require '[schema-tools.core :as st])

(s/defschema Entries
    {:entries [(st/merge Entry UuidParam)]})

(-> Entries :entries first meta)
; nil
```

**Comment by oliyh** [comment]
Kiitos @ikitommi and grazie @frankiesardo
